---
title: "Tutorial1"
author: "Lian van Vulpen"
date: "2026-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(network)
library(igraph)
library(reshape2)
library(tidyverse)
```

```{r}
url1 <- "https://github.com/rensec/sasr08/raw/main/g_adj_matrix_simple.csv"
g_matrix <- read.csv(file = url1, header = FALSE)
g_matrix
```
```{r}
class(g_matrix)
```

```{r}
g_matrix <- as.matrix(g_matrix)
g_matrix
class(g_matrix)
```

```{r}
rownames(g_matrix) <- 1:nrow(g_matrix)
colnames(g_matrix) <- 1:ncol(g_matrix)
g_matrix
```

```{r}
g_nodes_age <- read.csv(file = "https://github.com/rensec/sasr08/raw/main/g_nodes_age.csv")
g_nodes_age
```

```{r}
g <- graph_from_adjacency_matrix(g_matrix)
class(g)
```

```{r}
g
```

```{r}
plot(g)
```

```{r}
g <- set_vertex_attr(g,
                     name = "age",
                     value = g_nodes_age$age)
```

```{r}
g_elist <- read.csv(file = "https://github.com/rensec/sasr08/raw/main/g_elist.csv")
g_elist
```

```{r}
g_from_elist <- graph_from_data_frame(g_elist)
plot(g_from_elist)
```

```{r}
g_from_elist <- graph_from_data_frame(g_elist, vertices = g_nodes_age)
plot(g_from_elist)
```

```{r}
g_adj_list <- read.csv(file = "https://github.com/rensec/sasr08/raw/main/g_adj_list.csv")
g_adj_list
```

```{r}
g_elist_from_alist <- g_adj_list
g_elist_from_alist <-  select(g_elist_from_alist, id, friend1:friend2) # keep only the network variables (and id)
g_elist_from_alist <-  melt(g_elist_from_alist, id.vars = "id") # from the reshape2 package
g_elist_from_alist
```

```{r}
g_elist_from_alist <- g_adj_list %>%
  select(id, friend1:friend2) %>%
  melt(id.vars = "id")
```


```{r}
g_adj_list %>% # (we don't save it into an object as above this time, since we just want to show that the result is the same)
  select(id, friend1:friend2) %>% #keep only the network variables (and id)
  pivot_longer(c(friend1, friend2))

```
```{r}
g_elist_from_alist <- g_elist_from_alist%>%
  filter(!is.na(value)) %>%
  rename(from ="id", to = "value", sourcevar= "variable") %>%
  relocate(to, .after=from)
g_elist_from_alist
```

```{r}
g_from_alist <- graph_from_data_frame(g_elist_from_alist) #This is a proper igraph graph object
plot(g_from_alist)

```

```{r}
nodelist <- select(g_adj_list,id,age)
g_from_alist <- graph_from_data_frame(g_elist_from_alist, vertices = nodelist) #This is a proper igraph graph object
plot(g_from_alist)
```

# pipeline from adjacency list to igraph
```{r}
igraph_adj_list <- g_adj_list %>%
  select(id, friend1:friend2) %>%
  melt(id.vars = "id") %>%
  filter(!is.na(value)) %>%
  rename(from ="id", to = "value", sourcevar= "variable") %>%
  relocate(to, .after=from) %>%
  graph_from_data_frame( , vertices = select(g_adj_list, id, age)) %>%
  plot()





```

# 1.2.1

```{r}
g_adj_matrix <- as_adjacency_matrix(g, sparse = FALSE)
g_adj_matrix
```
```{r}
all(g_adj_matrix == g_matrix)
```
```{r}
g_edgelist <- igraph::as_data_frame(g_from_elist, what = "edges") 
g_edgelist
```
```{r}
igraph::as_data_frame(g_from_elist, what = "vertices") 
```

```{r}
edgelist_2 <- igraph::as_data_frame(g_from_alist, what = "edges")
nodelist_2 <- igraph::as_data_frame(g_from_alist, what = "vertices")
# Note the use of the "namespace" "igraph::" here, to indicate that we need the igraph function here, not the function with the same name from the dplyr/tidyverse package

d <- edgelist_2 %>%
  rename(id = "from") %>% 
  pivot_wider( id_cols = id, names_from = sourcevar, values_from = to ) %>% 
  merge(nodelist_2, by.x = "id", by.y = "name", all.y = TRUE ) %>% 
  relocate(age, .after = id) %>% 
  type_convert() #as_data_frame returns characters; this transforms it back to numeric
```
# 1.3
```{r}
g_np <- as.network(g_elist_from_alist, matrix.type = "edgelist", vertices = nodelist)
g_np
```

```{r}
plot(g_np)
```

```{r}
g_mod <- delete_vertices(g,2)
plot(g_mod)
```

```{r}
g_mod <- delete_vertices(g,which(V(g)$age == 21))
plot(g_mod)
```

```{r}
V(g)$gender <- c("male", "female", "female", "other", "male") 
g
```
```{r}
g_rev <- reverse_edges(g)
plot(g_rev)
```

```{r}
g_union <- igraph::union(g, g_rev)
```

```{r}
plot(g_union)
```

# 2
## 2.1




